// based on https://en.wikipedia.org/wiki/Glycolysis

var GlyElements = {
  nodes: [
    { data: {id: 0,planet: "Sun",type: "star",image: 'assets/2pg.svg',url: 'https://en.wikipedia.org/wiki/Sun'}}, 
	{data: {id: 1,planet: "Mercury",type: "planet",image: 'assets/2pg.svg',url: 'https://en.wikipedia.org/wiki/Glucose_6-phosphate'}}, 
	{data: {id: 2,planet: "Venus",image: 'assets/2pg.svg',type: "planet",url: 'https://en.wikipedia.org/wiki/Venus'}}, 
	{data: {id: 3,planet: "Earth",image: 'assets/2pg.svg',type: "planet",url: 'https://en.wikipedia.org/wiki/Earth'}},
    {data: {id: 4,planet: "Moon",image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Moon'}}, 
	{data: {id: 5,planet: "Mars",image: 'assets/2pg.svg',type: "planet",url: 'https://en.wikipedia.org/wiki/Mars'}}, 
	{data: {id: 6,planet: "Jupiter",image: 'assets/2pg.svg',type: "planet",url: 'https://en.wikipedia.org/wiki/Jupiter'}}, 
	{data: {id: 7,planet: "Io",image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Io_(moon)'}}, 
	{data: {id: 8,planet: "Europa",image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Europa_(moon)'}}, 
	{data: {id: 9,planet: "Ganymede",image: 'assets/2pg.svg',type: "moon",url:'https://en.wikipedia.org/wiki/Ganymede_(moon)'}}, 
	{data: {id: 10,planet: 'Callisto',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Callisto_(moon)'}},
	{data: {id: 11,planet: 'Saturn',image: 'assets/2pg.svg',type: "planet",url: 'https://en.wikipedia.org/wiki/Saturn'}},
	{data: {id: 12,planet: 'Titan',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Titan_(moon)'}},
	{data: {id: 13,planet: 'Rhea',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Rhea_(moon)'}},
	{data: {id: 14,planet: 'Iapetus',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Iapetus_(moon)'}},
	{data: {id: 15,planet: 'Dione',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Dione_(moon)'}},
	{data: {id: 16,planet: 'Tethys',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Tethys_(moon)'}},
	{data: {id: 17,planet: 'Enceladus',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Enceladus'}},
	{data: {id: 18,planet: 'Mimas',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Mimas_(moon)'}},
	{data: {id: 19,planet: 'Uranus',image: 'assets/2pg.svg',type: "planet",url: 'https://en.wikipedia.org/wiki/Uranus'}},
	{data: {id: 20,planet: 'Titania',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Titania_(moon)'}},
	{data: {id: 21,planet: 'Oberon',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Oberon_(moon)'}},
	{data: {id: 22,planet: 'Ariel',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Ariel_(moon)'}},
	{data: {id: 23,planet: 'Umbriel',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Umbriel_(moon)'}},
	{data: {id: 24,planet: 'Miranda',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Miranda_(moon)'}},
	{data: {id: 25,planet: 'Neptune',image: 'assets/2pg.svg',type: "planet",url: 'https://en.wikipedia.org/wiki/Neptune'}},
	{data: {id: 26,planet: 'Triton',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Triton_(moon)'}},
	{data: {id: 27,planet: 'Pluto',image:'assets/2pg.svg',type: "planet",url: 'https://en.wikipedia.org/wiki/Pluto'}},
	{data: {id: 28,planet: 'Eris',image: 'assets/2pg.svg',type: "dwarf planet",url: 'https://en.wikipedia.org/wiki/Eris_(dwarf_planet)'}},
	{data: {id: 29,planet: 'Makemake',image: 'assets/2pg.svg',type: "dwarf planet",url: 'https://en.wikipedia.org/wiki/Makemake'}},
	{data: {id: 30,planet: 'Charon',image: 'assets/2pg.svg',type: "moon",url: 'https://en.wikipedia.org/wiki/Charon_(moon)'}}
  ],
  
  edges: [
    {data: {id: 102,path: 'From Mercury to Venus',source: 1,target: 2}}, 
	{data: {id: 201,path: 'From Venus to Mercury',source: 2,target: 1}}, 
	{data: {id: 203,path: 'From Venus to Earth',source: 2,target: 3}}, 
	{data: {id: 302,path: 'From Earth to Venus',source: 3,target: 2}},
	{data: {id: 403,path: "From Moon to Earth",source: 4,target: 3}}, 
	{data: {id: 305,path: "From Earth to Mars",source: 3,target: 5}}, 
	{data: {id: 503,path: "From Mars to Earth",source: 5,target: 4}}, 
	{data: {id: 506,path: 'From Mars to Jupiter',source: 5,target: 6}},
	{data: {id: 605,path: 'From Jupiter to Mars',source: 6,target: 5}},
    {data: {id: 607,path: 'From Jupiter to Io',source: 6,target: 7}}, 
	{data: {id: 706,path: 'From Io to Jupiter',source: 7,target: 6}}, 
	{data: {id: 608,path: 'From Jupiter to Europa',source: 6,target: 8}}, 
	{data: {id: 806,path: 'From Europa to Jupiter',source: 8,target: 6}},
	{data: {id: 609,path: 'From Jupiter to Ganymede',source: 6,target: 9}},
	{data: {id: 906,path: 'From Ganymede to Jupiter',source: 9,target: 6}}, 	
	{data: {id: 6010,path: 'From Jupiter to Callisto',source: 6,target: 10}}, 
	{data: {id: 1006,path: 'From Callisto to Jupiter',source: 10,target: 6}},
	{data: {id: 6011,path: 'From Jupiter to Saturn',source: 6,target: 11 }},
	{data: {id: 1106,path: 'From Saturn to Jupiter',source: 11,target: 6 }},
	{data: {id: 11012,path: 'From Saturn to Titan',source: 11,target: 12}},
	{data: {id: 12011,path: 'From Titan to Saturn',source: 12,target: 11}},
	{data: {id: 11013,path: 'From Saturn to Rhea',source: 11,target: 13}},
	{data: {id: 13011,path: 'From Rhea to Saturn',source: 13,target: 11}},
	{data: {id: 11014,path: 'From Saturn to Iapetus',source: 11,target: 14}},
	{data: {id: 14011,path: 'From Iapetus to Saturn',source: 14,target: 11}},
	{data: {id: 11015,path: 'From Saturn to Dione',source: 11,target: 15}},
	{data: {id: 15011,path: 'From Dione to Saturn',source: 15,target: 11}},
	{data: {id: 11016,path: 'From Saturn to Tethys',source: 11,target: 16}},
	{data: {id: 16011,path: 'From Tethys to Saturn',source: 16,target: 11}},
	{data: {id: 11017,path: 'From Saturn to Enceladus',source: 11,target: 17}},
	{data: {id: 17011,path: 'From Enceladus to Saturn',source: 17,target: 11}},
	{data: {id: 11018,path: 'From Saturn to Mimas',source: 11,target: 18}},
	{data: {id: 18011,path: 'From Mimas to Saturn',source: 18,target: 11}},
	{data: {id: 11019,path: 'From Saturn to Uranus',source: 11,target: 19}},
	{data: {id: 19011,path: 'From Uranus to Saturn',source: 19,target: 11}},
	{data: {id: 19020,path: 'From Uranus to Titania',source: 19,target: 20}},
	{data: {id: 20019,path: 'From Titania to Uranus',source: 20,target: 19}},
	{data: {id: 19021,path: 'From Uranus to Oberon',source: 19,target: 21}},
	{data: {id: 21019,path: 'From Uranus to Oberon',source: 21,target: 19}},
	{data: {id: 19022,path: 'From Uranus to Ariel',source: 19,target: 22}},
	{data: {id: 22019,path: 'From Ariel to Uranus',source: 22,target: 19}},
	{data: {id: 19023,path: 'From Uranus to Umbriel',source: 19,target: 23}},
	{data: {id: 23019,path: 'From Umbriel to Uranus',source: 23,target: 19}},
	{data: {id: 19024,path: 'From Uranus to Miranda',source: 19,target: 24}},
	{data: {id: 24019,path: 'From Miranda to Uranus',source: 24,target: 19}},
	{data: {id: 19025,path: 'From Uranus to Neptune',source: 19,target: 25}},
	{data: {id: 25019,path: 'From Neptune to Uranus',source: 25,target: 19}},
	{data: {id: 25026,path: 'From Neptune to Triton',source: 25,target: 26}},
	{data: {id: 26025,path: 'From Triton to Neptune',source: 26,target: 27}},
	{data: {id: 25027,path: 'From Neptune to Pluto',source: 25,target: 27}},
	{data: {id: 27025,path: 'From Pluto to Neptune',source: 27,target: 25}},
	{data: {id: 27028,path: 'From Pluto to Eris',source: 27,target: 28}},
	{data: {id: 28027,path: 'From Eris to Pluto',source: 28,target: 27}},
	{data: {id: 27029,path: 'From Pluto to Makemake',source: 27,target: 29}},
	{data: {id: 29027,path: 'From Makemake to Pluto',source: 29,target: 27}},
	{data: {id: 27030,path: 'From Pluto to Charon',source: 27,target: 30}},
	{data: {id: 30027,path: 'From Charon to Pluto',source: 30,target: 27}}	
  ]
};
